import "./assets/styles/global.css";
import { ReactNode } from "react";

export const metadata = {
    title: "Cat² - Le chat qui bâtit ton trésor une pelle à la fois",
    description: "Generated by Next.js",
    icons: {
        icon: "/favicon.ico",
    },
};

export default function RootLayout({ children }: { children: ReactNode }) {
    return (
        <html lang="fr">
            <body>
                <header>
                    <h1>Cat²</h1>
                </header>
                <main>{children}</main>
                <footer>
                    <p>© 2024 Cat². Tous droits réservés.</p>
                </footer>
            </body>
        </html>
    );
}
