export const metadata = {
  title: 'Cat² - Le chat qui bâtit ton trésor une pelle à la fois',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
