import { ReactNode } from "react";

import "./assets/styles/Global.css";

import Header from "../components/Header/Header";
import Footer from "../components/Footer/Footer";

export const metadata = {
    title: "Cat² - Le chat qui bâtit ton trésor une pelle à la fois",
    description: "Generated by Next.js",
    icons: {
        icon: "/favicon.ico",
    },
};

export default function RootLayout({ children }: { children: ReactNode }) {
    return (
        <html lang="fr">
            <body>
                <Header />
                <main className="mainWrapper">{children}</main>
                <Footer />
            </body>
        </html>
    );
}
